### ISSUE TITLE
Atualização para suporte a versões mais recentes do WordPress e FacebookOpenGraph

### ISSUE THREAD

**Issue by JoseCage** [mariovalney/og-tags#1]
Olá @mariovalney. Dei uma olhada no seu plugin e acho bem interessante. Mas reparei que o plugin não é atualizado entre 2 a 3 anos, o que pode estar deixando pra trás algumas funcionalidades novas implementadas quer no wordpress como na API do FacebookOpenGraph..
  No caso eu sugeria que podesse dar uma olhada por esse lado e então fazer atualização..

Valeu.. :facepunch:

**Comment by mariovalney** [comment]
Obrigado pelo comentário, @JoseCage. 
O maior problema é a falta de tempo. Esse plugin é bem antigo e qualquer alteração que farei, terei que refatorá-lo completamente para os padrões do WordPress.

De qualquer forma, o problema é tempo, mas estou trabalhando para que saia uma atualização nas próximas semanas. Obrigado.

**Comment by JoseCage** [comment]
De boa @mariovalney  :smiley: 

Aguardando pelas novidades..

**Comment by mariovalney** [comment]
@JoseCage consegui terminar a versão 2.0.
Infelizmente não pude fazer nenhuma melhoria, porém o código foi totalmente refatorado e agora está seguindo os padrões do WordPress e orientação a objeto.

Commit: https://github.com/mariovalney/og-tags/commit/f6eb71729f201f719e51bdefe0462b0c18e8d0df

**Comment by JoseCage** [comment]
Que massa @mariovalney .. Vou dar uma olhada e testar..
